name: azure bicep deploy

on: 

push: 
  branches: ["master"]

  jobs:
   
   build:

      runs-on: ubuntu-latest

      steps:

      - uses: actions/checkout@v3

      - name: Echo script
        run: echo starting bicep..

      - name: login with azure
        uses: azure/login@v1
        with: 
          creds: '${{ secrets.AZURE_CREDENTIALS }}'

        -name: Deploy the Bicep script
         uses: azure/arm-deploy@v2
         with:
            resourceGroupName: "WebAppGroup"
            template: azure-resource.bicep 